
export const userConstants = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILURE: 'LOGOUT_FAILURE',
}

export const postConstants = {
    POST_REQUEST: 'POST_REQUEST',
    POST_GET_ALL_SUCCESS: 'POST_GET_ALL_SUCCESS',
    POST_GET_ALL_FAILURE: 'POST_GET_ALL_FAILURE',
    POST_GET_SUCCESS: 'POST_GET_SUCCESS',
    POST_GET_FAILURE: 'POST_GET_FAILURE',
    POST_CREATE_SUCCESS: 'POST_CREATE_SUCCESS',
    POST_CREATE_FAILURE: 'POST_CREATE_FAILURE',
    POST_EDITED_SUCCESS: 'POST_EDITED_SUCCESS',
    POST_EDITED_FAILURE: 'POST_EDITED_FAILURE',
    POST_DELETE_SUCCESS: 'POST_DELETE_SUCCESS',
    POST_DELETE_FAILURE: 'POST_DELETE_FAILURE',
}

export const commentConstants = {
    COMMENT_REQUEST: 'COMMENT_REQUEST',
    COMMENT_GET_ALL_SUCCESS: 'COMMENT_GET_ALL_SUCCESS',
    COMMENT_GET_ALL_FAILURE: 'COMMENT_GET_ALL_FAILURE',
    COMMENT_GET_SUCCESS: 'COMMENT_GET_SUCCESS',
    COMMENT_GET_FAILURE: 'COMMENT_GET_FAILURE',
    COMMENT_ADD_SUCCESS: 'COMMENT_ADD_SUCCESS',
    COMMENT_ADD_FAILURE: 'COMMENT_ADD_FAILURE',
    COMMENT_REPLAY_SUCCESS: 'COMMENT_REPLAY_SUCCESS',
    COMMENT_REPLAY_FAILURE: 'COMMENT_REPLAY_FAILURE',
    COMMENT_EDITED_SUCCESS: 'COMMENT_EDITED_SUCCESS',
    COMMENT_EDITED_FAILURE: 'COMMENT_EDITED_FAILURE',
    COMMENT_DELETE_SUCCESS: 'COMMENT_DELETE_SUCCESS',
    COMMENT_DELETE_FAILURE: 'COMMENT_DELETE_FAILURE',
}

